language: node_js
sudo: false
node_js:
  - "5.0"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - couchdb
  - redis
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - curl -X PUT localhost:5984/oose
  - >
    curl -X PUT "http://localhost:5984/_users/org.couchdb.user:oose"
    -H "Accept: application/json" -H "Content-Type: application/json"
    -d '{"name": "oose", "password": "blah1234", "roles": [], "type": "user"}'